### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by infosisio** [amilajack/popcorn-time-desktop#554] opened 2019-04-03 00:34 UTC
Click on a film and all you get is "Welcome to popcorn time printed"
I've tried all latest Linux builds.

**Comment by amilajack** [comment] 2019-04-03 02:29
Yea I can reproduce this. Try cloning next branch and build from source. I'll cut a new release soon

**Comment by amilajack** [comment] 2019-04-03 18:24
Can you please try the [1.3.0](https://github.com/amilajack/popcorn-time-desktop/releases/tag/v1.3.0) release and lmk if this works for you? Thanks!

**Comment by infosisio** [comment] 2019-04-03 21:51
Nope, I no longer get that message but the movie is not loading either.
Tried the amd64 deb.

**Comment by amilajack** [comment] 2019-04-04 21:28
I can reproduce that. Please try the [1.3.1](https://github.com/amilajack/popcorn-time-desktop/releases/tag/v1.3.1) release. This should work

**Comment by KurtDeGreeff** [comment] 2019-04-05 18:45
Hi, just downloaded version 1.3.1 for windows, tried setup and portable version. I get list wirh movies but on any I click on I get blank dark screen..
![image](https://user-images.githubusercontent.com/2629743/55649608-af321b00-57e3-11e9-9d38-9835212f27df.png)

**Comment by legluondunet** [comment] 2019-04-05 21:58
Hello, Ubuntu 18.04, like @KurtDeGreeff  I can launch the 1.3.1 appimage, Popcorn launch, show movies thumbnails but I obtain only a black window instead of the movie.

**Comment by amilajack** [comment] 2019-04-05 22:18
@infosisio @legluondunet @KurtDeGreeff Alright I promise [1.3.2](https://github.com/amilajack/popcorn-time-desktop/releases/tag/v1.3.2) will work. Sorry for the back and forth.

**Comment by legluondunet** [comment] 2019-04-06 06:14
same result with the 1.3.2, could you reopen this issue? How to help you to debug this issue? Is there a log file?

**Comment by KurtDeGreeff** [comment] 2019-04-06 12:33
For me also still same issue with v1.3.2. like v1.3.1 just dark screen. Much appreciated for resolving this.

**Comment by amilajack** [comment] 2019-04-06 17:03
The app currently doesnt have any kind of logging support at the moment. What would help me debug is knowing what OS you're running on and then uploading screenshots of what you see. I've tested both windows and linux and both dong have dark screens. I can confirm that on linux, there isn't any playback. I can confirm tho that cloning from source and running dev build works for me.

**Closed** 2019-04-20 17:39 UTC
