### ISSUE TITLE
Product detail page only says "Welcome to PopcornTime"

### ISSUE THREAD

**Issue by probonopd** [amilajack/popcorn-time-desktop#303] opened 2018-09-07 17:37 UTC
## Issue Name

Product detail page only says "Welcome to PopcornTime"

### What did you do?

Click on any movie

### What did you expect to happen?

A movie detail page appears

### What actually happened?

Product detail page only says "Welcome to PopcornTime"

#### System Configuration

* App Version: 1.2.0 (snap and AppImage)
* Operating System: Xubuntu 18.04 LTS
* Node Version: Whichever comes with the snap and AppImage
* npm version: Whichever comes with the snap and AppImage

#### Errors

Nothing shown on the console

#### Screenshot/gif

![Screenshot](https://user-images.githubusercontent.com/2480569/45234266-b7b18a00-b2c4-11e8-81fa-b92a682e7eac.png)

**Comment by amilajack** [comment] 2018-09-07 17:49
What branch are you on?

**Comment by amilajack** [comment] 2018-09-07 17:52
Are you downloading from releases or building your own release

**Comment by probonopd** [comment] 2018-09-07 20:14
Downloading from GitHub Releases

**Comment by amilajack** [comment] 2018-09-09 02:52
I can't seem to reproduce this. I am running on ubuntu 18 and it works fine for me

**Comment by probonopd** [comment] 2018-09-09 15:37
Can I switch to some verbose mode or somehow assist in debugging?

**Comment by amilajack** [comment] 2018-09-09 16:09
Error reporting isnt setup for this project yet and there is no debugging mode so unfortunately the only way to reproduce it is by cloning from source and run it:
```bash
git clone https://github.com/amilajack/popcorn-time-desktop
cd popcorn-time-desktop
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.8 icnsutils graphicsmagick  xz-utils  xorriso gcc-multilib  g++-multilib  rpm libavahi-compat-libdnssd-dev  avahi-daemon  avahi-discover
npm i -g yarn
yarn
yarn dev
```

**Comment by probonopd** [comment] 2018-09-09 16:14
Sorry, I won't be compiling it myself. Do you have a chance to grab a Xubuntu 18.04 Live ISO and run the AppImage there?

**Comment by KirkBushman** [comment] 2018-11-15 21:36
I get the same thing on fedora 29, both AppImage and rpm.
I'm willing to help, but I don't really know what to look for since I didn't look at the code.

I see the lists of films, when I click on 1, I see welcome to popcorn time.
The elements in the root div at that point is just a few divs and the text "Welcome to PopcornTime"

On the console I don't see any errors, just @@router/LOCATION_CHANGE

On the terminal I see:
Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry
but I don't know if it's meaningful, It's doing it since the opening of the app...

Should I be looking for something else?

**Comment by amilajack** [comment] 2018-11-15 21:38
Can you send the entire stacktrace

**Comment by KirkBushman** [comment] 2018-11-16 08:13
Uncaught (in promise) Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (/home/luca/Downloads/popcorn-time-desktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at Object.<anonymous> (/home/luca/Downloads/popcorn-time-desktop/app/node_modules/mdns/lib/dns_sd.js:32)
    at Object.<anonymous> (/home/luca/Downloads/popcorn-time-desktop/app/node_modules/mdns/lib/dns_sd.js:39)
    at Module._compile (module.js:642)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)




GET https://image.tmdb.org/t/p/w342/null 404 ()
componentWillReceiveProps	@	Home.js:192
callComponentWillReceiveProps	@	react-dom.development.js:12564
updateClassInstance	@	react-dom.development.js:12774
updateClassComponent	@	react-dom.development.js:14260
beginWork	@	react-dom.development.js:15087
performUnitOfWork	@	react-dom.development.js:17809
workLoop	@	react-dom.development.js:17849
renderRoot	@	react-dom.development.js:17935
performWorkOnRoot	@	react-dom.development.js:18823
performWork	@	react-dom.development.js:18735
performSyncWork	@	react-dom.development.js:18709
requestWork	@	react-dom.development.js:18578
scheduleWork	@	react-dom.development.js:18387
enqueueSetState	@	react-dom.development.js:12313
Component.setState	@	react.development.js:372
onStateChange	@	connectAdvanced.js:221
onStateChange	@	react-hot-loader.development.js:587
dispatch	@	redux.js:222



I'm in /item/movies/335983

**Comment by KirkBushman** [comment] 2018-11-16 08:15
Anyway I've tried another pc with fedora 29 and I'm seeing the same behaviour.
You can try to install it in live usb environment for testing.

**Comment by amilajack** [comment] 2018-11-16 18:16
So you're cloning the repo right? If you are it makes sense you're running into that issue. You don't have native dependencies installed. For linux you will need [these dependencies](https://github.com/amilajack/popcorn-time-desktop/blob/v1.2.0/.travis.yml#L24-L35)

**Comment by KirkBushman** [comment] 2018-11-17 07:56
Keep in mind those are not for linux in general, but specifically ubuntu, for example in fedora the libs are different:

icnsutils -> libicns-utils
graphicsmagick -> GraphicsMagick
xz-utils -> xz
gcc-multilib -> gcc gcc-c++
avahi-daemon,
avahi-discover -> avahi
libnss-mdns -> nss-mdns

And even after installing all of those the problem is still here.
I suggest you do a test on fedora.

I did the installation process again, and I realized it fails on mdns: 

    Error: /usr/bin/node exited with code 1
    Output:
    yarn install v1.12.3
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    
    Error output:
    error /home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns: Command failed.
    Exit code: 1
    Command: node-gyp rebuild
    Arguments: 
    Directory: /home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns
    Output:
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.13.0 | linux | x64
    gyp info spawn /usr/bin/python2
    gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/username/.electron-gyp/iojs-2.0.13/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/username/.electron-gyp/iojs-2.0.13',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/username/.electron-gyp/iojs-2.0.13/<(target_arch)/iojs.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    make: Entering directory '/home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns/build'
      CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
    In file included from ../src/dns_sd.cpp:1:
    ../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
     #include <dns_sd.h>
              ^~~~~~~~~~
    compilation terminated.
    make: *** [dns_sd_bindings.target.mk:162: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
    make: Leaving directory '/home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
    gyp ERR! System Linux 4.18.18-300.fc29.x86_64
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/username/Downloads/popcorn-time-desktop/app/node_modules/mdns
    gyp ERR! node -v v10.13.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    
        at ChildProcess.childProcess.once.code (/home/username/Downloads/popcorn-time-desktop/node_modules/builder-util/src/util.ts:253:14)
        at Object.onceWrapper (events.js:273:13)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:962:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
    From previous event:
        at _installOrRebuild (/home/username/Downloads/popcorn-time-desktop/node_modules/app-builder-lib/out/util/yarn.js:71:28)
        at installOrRebuild (/home/username/Downloads/popcorn-time-desktop/node_modules/app-builder-lib/out/util/yarn.js:55:28)
        at /home/username/Downloads/popcorn-time-desktop/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
        at Generator.next (<anonymous>)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
    From previous event:
        at _installAppDeps (/home/username/Downloads/popcorn-time-desktop/node_modules/electron-builder/out/cli/install-app-deps.js:176:26)
        at installAppDeps (/home/username/Downloads/popcorn-time-desktop/node_modules/electron-builder/out/cli/install-app-deps.js:144:26)
        at then (/home/username/Downloads/popcorn-time-desktop/node_modules/electron-builder/src/cli/cli.ts:46:19)
    error Command failed with exit code 1.

**Comment by probonopd** [comment] 2018-12-01 09:06
It needs to be bundled into the AppImage then.

**Closed** 2021-03-19 18:32 UTC
Labels: bug
